name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        
    - name: Run linting
      run: |
        flake8 src tests
        mypy src tests
        black --check src tests
        
    - name: Run tests
      run: |
        pytest -q --cov=src --cov-report=term-missing
        
    - name: Check coverage
      run: |
        coverage report --fail-under=80
        
    - name: Run sample simulation
      run: |
        python -m src.sim.run_sim --count 5 --mode zta --seed 1 --out data/test_events.jsonl
        test -f data/test_events.jsonl
        
    - name: Run sample experiment
      run: |
        python -m src.sim.experiment --config configs/sample_experiment.json --mode zta --run-id ci_test --seed 1
        test -d data/experiments/ci_test
        test -f data/experiments/ci_test/results.json
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: experiment-results
        path: data/experiments/