version: '3.8'

services:
  zta-sim:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    volumes:
      # Mount data directory for persistence
      - ../data:/app/data
      # Mount configs for easy modification
      - ../configs:/app/configs
      # Mount analysis outputs
      - ../analysis:/app/analysis
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "
        # Run experiment
        python -m src.sim.experiment --config configs/sample_experiment.json &&
        # Generate analysis
        python -m analysis.scripts.analyze_results --experiment data/experiments/$(ls -t data/experiments | head -n1) &&
        # Generate report
        python -m analysis.scripts.generate_report --experiment data/experiments/$(ls -t data/experiments | head -n1)
      "
